version: '3'
networks:
  macvlan_network:
    external: true

  
services:
  suno-api:
    build:
      context: .
      args:
        SUNO_COOKIE: ${SUNO_COOKIE}
    volumes:
      - ./public:/app/public
    ports:
      - "3000:3000"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    networks:
      macvlan_network:
        ipv4_address: 192.168.1.125